# Generated by Django 2.1 on 2019-08-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xfzauth', '0004_auto_20190709_2007'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
